# Site Info
title:              "The Nerd Lawyer"
description:        "From time to time I share my noodlings about law and the practice thereof, technology, entertainment, digital media, and how to spend more time than you could possibly save automating and enhancing your workflow with OmniFocus, DevonThink, MailMate, Hammerspoon, Karabiner, TextExpander, Hazel, Launchbar, Keyboard Maestro, Shortcat, and a rudimentary grasp of various programming languages."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-69828722-1 # Put your Google Analytics code

# Author Info
author_name:        "Michael B. Smith"
author_email:       mbs@nerd.lawyer
author_gravatar:    929667051a196fa7b33008fc359ed1c6 # Gravatar md5 hash
twitter_username:   thenerdlawyer
logo: scales-glasses-logo.png

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        pygments
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
  - jekyll-feed

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
